# Independent settings for the planner's costmap
global_costmap:
  map_type: costmap

  global_frame    : map
  robot_base_frame: base_footprint

  update_frequency : 10.0
  publish_frequency: 1.0

  transform_tolerance: 0.2

  track_unknown_space: true
  unknown_cost_value : 255

  robot_radius: 0.275

  #plugins are loaded in a separate yaml file

  static_layer:
    enabled  : true
    map_topic: map

  obstacle_laser_layer:
    enabled: true
    observation_sources: base_scan
    combination_method: 0 # can erase static layer

    base_scan:
      sensor_frame: base_laser_link
      data_type: LaserScan
      topic: scan
      expected_update_rate: 0.3
      observation_persistence: 1.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 4.0
      obstacle_range: 3.5
      min_obstacle_height: -0.1
      max_obstacle_height: 0.4

  obstacle_sonar_layer:
    enabled: false
    observation_sources: sonar_cloud sonar_max_range_cloud
    combination_method: 1

    sonar_cloud:
      sensor_frame: base_link
      data_type: PointCloud2
      topic: sonar_cloud
      expected_update_rate: 1.0
      observation_persistence: 0.0
      marking: true
      clearing: true
      raytrace_range: 4.5
      obstacle_range: 3.0
      min_obstacle_height: 0.1
      max_obstacle_height: 1.8

    sonar_max_range_cloud:
      sensor_frame: base_link
      data_type: PointCloud2
      topic: sonar_max_range_cloud
      expected_update_rate: 1.0
      observation_persistence: 0.0
      marking: false
      clearing: true
      raytrace_range: 4.5
      obstacle_range: 3.0
      min_obstacle_height: 0.1
      max_obstacle_height: 1.8

  obstacle_vo_layer:
    enabled: true
    observation_sources: vo_cloud
    combination_method: 1

    vo_cloud:
      sensor_frame: base_link
      data_type: PointCloud
      topic: vo_cloud
      expected_update_rate: 12.0
      observation_persistence: 0.0
      marking: true
      clearing: false
      raytrace_range: 1.0
      obstacle_range: 20.0
      min_obstacle_height: 0.0
      max_obstacle_height: 2.0

  obstacle_rgbd_layer:
    enabled: true
    observation_sources: rgbd_scan
    combination_method: 1

    rgbd_scan:
      sensor_frame: rgbd_laser_link
      data_type: LaserScan
      topic: rgbd_scan
      expected_update_rate: 0.2
      observation_persistence: 0.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 2.9
      obstacle_range: 2.8
      blanking_range: 1.55
      mark_blanking: true
      min_obstacle_height: -0.1
      max_obstacle_height: 0.2
      debug: false

  inflation_layer:
    enabled            : true
    inflation_radius   : 0.55
    cost_scaling_factor: 25.0
